### ISSUE TITLE
Vậy giá trị của n ở đây có thể âm được không bạn ? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/BinNoob#1]
https://github.com/thoaikhoa14402/BinNoob/blob/4cec03c11f21b668d0620c82e418d6f5f0350166/InSao.cpp#L6-L8

**Comment by thoaikhoa14402** [comment]
dạ không ạ, em bị thiếu bước bắt điều kiện, sẽ chú ý hơn ạ
