### ISSUE TITLE
Tại sao khi mình nhập giá trị n = 4 thì chương trình cho ra output là The greatest number is : Number 1 : ? Liệu có thể chia thành các hàm nhỏ nữa được không ? Tại sao lại dùng if-else trong vòng lặp do-while(có ý đồ gì ở đây) ? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/BinNoob#10]
https://github.com/thoaikhoa14402/BinNoob/blob/22987ae75e0a32b699c1f31ee1e3e8e700038141/3.1%20-%20Code.cpp#L44-L55
<img width="311" alt="image" src="https://user-images.githubusercontent.com/52942703/111891559-a4034480-8a26-11eb-82f0-f66078608b40.png">

**Comment by thoaikhoa14402** [comment]
![image](https://user-images.githubusercontent.com/81000230/111966621-b4501800-8b29-11eb-8dd8-c77b51d769e9.png)
Em nhập n  = 4 nó vẫn hiện từ number 1 đến number 4 mà ạ

**Comment by toniminh161200** [comment]
Bạn dùng if-else trong vòng lặp do-while khi cả hai đều dùng 1 điều kiện là sao nhỉ ?

**Comment by thoaikhoa14402** [comment]
dạ để em rút kinh nghiệm ạ
