### ISSUE TITLE
Tại sao lại dùng if (n<0) trong vòng lặp do-while(n<0) ????? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/BinNoob#12]
https://github.com/thoaikhoa14402/BinNoob/blob/22987ae75e0a32b699c1f31ee1e3e8e700038141/3.1%20-%20Code.cpp#L103-L111

**Comment by thoaikhoa14402** [comment]
để cout cái invalid age á anh @@

**Comment by toniminh161200** [comment]
Vậy cho mình hỏi thế bạn dùng vòng lặp do-while với điều kiện của vòng lặp là gì vậy ? 
```C++ 
do {
} while ( n < 0 );
```

**Comment by thoaikhoa14402** [comment]
Dạ có nghĩ là nếu ng dùng vẫn nhập tuổi nhỏ hơn 0 thì nó sẽ cout cái invalid age ra, sau đó thực hiện lại các bước nhập. Nếu người dùng nhập tuổi lớn hơn 0 tức tuổi hợp lệ thì nó sẽ ko thực hiện cái if, đồng thời cái while sẽ ko làm nữa ạ

**Comment by toniminh161200** [comment]
Nhưng bạn trông thấy 
```C++
if (n < 0) 
```
ở trong vòng lặp do - while thực hiện điều kiện như vậy bạn có thấy logic k ? . Nếu muốn như vậy thì bạn chỉ cần chèn thông điệp rằng 
``` C++
cout << "Please enter your age (age > 0)"; cin >> n;
```
là được chứ k cần phải `if` ở trong vòng lặp `do-while` đâu (nếu như cùng sử dụng 1 điều kiện)

**Comment by thoaikhoa14402** [comment]
dạ cảm ơn anh góp ý, tại em sợ người dùng vẫn nhập sai thì ct nó bị lỗi ấy ạ
