### ISSUE TITLE
Vậy kiểu trả về cho từng kiểu dữ liệu là gì ? Nếu như giả sử kiểu dữ liệu bool thì kiểu trả về là bool á bạn hay có gì khác k ? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/BinNoob#3]
https://github.com/thoaikhoa14402/BinNoob/blob/c4aaf9e8f513706736900935e9393daaa5d1dc3a/3.1.txt#L14-L18

**Comment by thoaikhoa14402** [comment]
hàm có kiểu int gì return giá trị kiểu int, hàm bool thì return true hoặc false, hàm float gì kiểu trả về là float..... Chỉ có hàm void là không có giá trị trả về, còn các kiểu dữ liệu cơ bản đều có
