### ISSUE TITLE
?????? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/BinNoob#4]
https://github.com/thoaikhoa14402/BinNoob/blob/c4aaf9e8f513706736900935e9393daaa5d1dc3a/3.1.txt#L21-L22

**Comment by thoaikhoa14402** [comment]
tham số hình thức là nó sẽ tạo ra một bản sao giống kiểu dữ liệu từ tham số thực truyền vào hàm, nếu truyền & là truyền địa chỉ thì nó sẽ là truyền tham chiếu, những gì tương tác bên trong hàm thì bên ngoài hàm sẽ bị ảnh hưởng, còn không  truyền dấu & thì nó chỉ làm việc trên bản sao, ra khỏi hàm ko ảnh hưởng đến các tham số thực tuyền vào

**Comment by toniminh161200** [comment]
Nếu mình không nhầm bạn đang nói về việc tham chiếu. Còn đây mình đang đề cập tới tham số hình thức và tham số thực. Nó chưa liên quan gì tới việc tham chiếu cả. Tham số hình thức bạn thử đoán nghĩa rồi trả lời lại câu này nhé

**Comment by thoaikhoa14402** [comment]
tham số hình thức là biến đc liệt kê trong danh sách tham số được truyền ở định nghĩa hàm, hàm sẽ thao tác với biến này
