### ISSUE TITLE
Tại sao lại là truyền địa chỉ ? Vậy thay đổi giá trị nào sau khi kết thúc lời gọi hàm ? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/BinNoob#5]
https://github.com/thoaikhoa14402/BinNoob/blob/c4aaf9e8f513706736900935e9393daaa5d1dc3a/3.1.txt#L25

**Comment by thoaikhoa14402** [comment]
dấu & là truyền địa chỉ, giá trị biến tham chiếu sẽ được thay đổi sau khi hàm kết thúc nếu trong hàm có tương tác với biến tham chiếu đó
