### ISSUE TITLE
Nếu như hàm đó chưa được định nghĩa hoặc không có kiểu trả về thì cách gọi hàm đó như thế nào ? 

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/BinNoob#6]
https://github.com/thoaikhoa14402/BinNoob/blob/c4aaf9e8f513706736900935e9393daaa5d1dc3a/3.1.txt#L30

**Comment by thoaikhoa14402** [comment]
nếu như muốn gọi hàm void ( hàm ko có kiểu trả về ) thì chỉ cần gọi tên hàm truyền vào tham số thực, còn nếu ham chưa được định nghĩa thì ct sẽ báo lỗi, muốn gọi nó thì phải khai báo prototype
